version: '3.1'

networks:
  rabbitmq-service:
    driver: bridge
services:
  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbitmq"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq"
    networks:
      - "rabbitmq-service"
  job:
    image: "rabbitmq-job:v1.0.0"
    ports:
      - "8080:8080"
    labels:
      NAME: "job"
    networks:
      - "rabbitmq-service"
    depends_on:
      - "rabbitmq"
    environment:
      - "SPRING_RABBITMQ_HOST=rabbitmq"
  worker:
    image: "rabbitmq-job:v1.0.0"
    ports:
      - "8081:8080"
    labels:
      NAME: "worker"
    networks:
      - "rabbitmq-service"
    depends_on:
      - "rabbitmq"
    environment:
      - "SPRING_RABBITMQ_HOST=rabbitmq"
  worker1:
    image: "rabbitmq-job:v1.0.0"
    ports:
      - "8082:8080"
    labels:
      NAME: "worker"
    networks:
      - "rabbitmq-service"
    depends_on:
      - "rabbitmq"
    environment:
      - "SPRING_RABBITMQ_HOST=rabbitmq"